version: "3.8"

services:
  microservicio:
    build: .
    container_name: microservicio-devops
    ports:
      - "8080:8080"
    restart: always
    environment:
      - APP_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M