name: Pipeline CI/CD EP2 DevOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, Security and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar proyecto con Maven
        run: mvn clean package

      - name: Ejecutar pruebas automatizadas
        run: mvn test

      - name: Escaneo de seguridad con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'

      - name: Construir imagen Docker
        run: docker build -t microservicio-devops:latest .

      - name: Despliegue simulado con Docker Compose
        run: docker compose up -d --build

      - name: Verificar contenedores activos
        run: docker ps